### ISSUE TITLE
Error objects renders as "Invalid object"

### ISSUE THREAD

**Issue by prvak** [firefox-devtools/devtools-core#1162] opened 2019-07-17 14:22 UTC
I have an Error object (thrown by axios library) that fails to render.

![Screenshot from 2019-07-17 15-32-24](https://user-images.githubusercontent.com/2436340/61379629-304f8280-a8a8-11e9-8d8a-f25f32a720b9.png)

This is in Firefox 67.0.4 (64-bit) on Linux.

Similar to: https://github.com/firefox-devtools/devtools-core/issues/1009 but callstack in my case is much shorter.

Edit:
Problem seems to be with the first line of the stacktrace. It is actually an error message, not a stack location. Here is a minimal example that reproduces the error:
```
<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
</head>
<body>
  <script >
    const e = new Error('Dummy error');
    e.stack="Error: Request failed with status code 403\ncreateError@webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15\n"
    console.log({e:e});
  </script>
</body>
</html>
```

**Comment by nchevobbe** [comment] 2019-07-17 16:01
Hey, thanks for the report !
I reproduced in 67, and it seems to be fixed in 68 (and also in Nightly, 70).
68 is now in release, could you try to update and tell us if everything is okay?

**Comment by prvak** [comment] 2019-07-17 16:14
Updated to 68 and it renders correctly now. Thank you!

**Closed** 2019-07-17 16:15 UTC
Labels: not-available
